//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primo.DevEx.Extensibility.Hackathon.HelloWorld.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelloWorldResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelloWorldResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primo.DevEx.Extensibility.Hackathon.HelloWorld.Data.HelloWorldResources", typeof(HelloWorldResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primo hello world cli command.
        /// </summary>
        public static string CommandDesc {
            get {
                return ResourceManager.GetString("CommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        public static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Validation error] {0} is not a valid style..
        /// </summary>
        public static string InvalidStyleOption {
            get {
                return ResourceManager.GetString("InvalidStyleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        public static string MessageDefaultValue {
            get {
                return ResourceManager.GetString("MessageDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -m.
        /// </summary>
        public static string MessageOptionAlias {
            get {
                return ResourceManager.GetString("MessageOptionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message description here.
        /// </summary>
        public static string MessageOptionDesc {
            get {
                return ResourceManager.GetString("MessageOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --message.
        /// </summary>
        public static string MessageOptionName {
            get {
                return ResourceManager.GetString("MessageOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all available styles within the &apos;hello&apos; command.
        /// </summary>
        public static string ShowStylesCommandDesc {
            get {
                return ResourceManager.GetString("ShowStylesCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liststyles.
        /// </summary>
        public static string ShowStylesCommandName {
            get {
                return ResourceManager.GetString("ShowStylesCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                        .-----.                                         
        ///                                   .-*#+=---=+#*-.                                     
        ///                                  =#+:   .+    :+#=                                    
        ///                                 *#-      #   +  :#*                                   
        ///                                =#-       # #*    -#+                                  
        ///                                ##.       #*       #*               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SitecoreHackathonLogo {
            get {
                return ResourceManager.GetString("SitecoreHackathonLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -s.
        /// </summary>
        public static string StyleOptionAlias {
            get {
                return ResourceManager.GetString("StyleOptionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plain.
        /// </summary>
        public static string StyleOptionDefaultValue {
            get {
                return ResourceManager.GetString("StyleOptionDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style description here.
        /// </summary>
        public static string StyleOptionDesc {
            get {
                return ResourceManager.GetString("StyleOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --style.
        /// </summary>
        public static string StyleOptionName {
            get {
                return ResourceManager.GetString("StyleOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trace] Validation of command options started.
        /// </summary>
        public static string TraceValidationBegin {
            get {
                return ResourceManager.GetString("TraceValidationBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trace] Validation of command options completed.
        /// </summary>
        public static string TraceValidationComplete {
            get {
                return ResourceManager.GetString("TraceValidationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Verbose] Hello World Command: Execute process started.
        /// </summary>
        public static string VerboseHelloWorldTaskBeginHeader {
            get {
                return ResourceManager.GetString("VerboseHelloWorldTaskBeginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Verbose] Hello World Command: Message = {0}.
        /// </summary>
        public static string VerboseHelloWorldTaskMessageOption {
            get {
                return ResourceManager.GetString("VerboseHelloWorldTaskMessageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Verbose] Hello World Command: Style = {0}.
        /// </summary>
        public static string VerboseHelloWorldTaskStyleOption {
            get {
                return ResourceManager.GetString("VerboseHelloWorldTaskStyleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Verbose] hello liststyles subcommand: Execute process started.
        /// </summary>
        public static string VerboseShowStylesTaskBeginHeader {
            get {
                return ResourceManager.GetString("VerboseShowStylesTaskBeginHeader", resourceCulture);
            }
        }
    }
}
